### PR TITLE
Adressing some Issues

### PR DESCRIPTION
**Pull request by Merulast**
#25 - Hardening against injections
#22 - Single block Tags

### CODE REVIEW

**Comment by patorjk** [comment]
Looked good, thanks!

**Comment by termermc** [comment]
@Merulast Thank you for addressing this, however I did notice some issues with escapes in securityFixes.
```js
function securityFixes(text) {
        return text
            .replaceAll("'", '&quot;') // This should be &#39; (&apos; is an XML entity, but is non-standard for HTML)
            .replaceAll('"', '&apos;') // This should be &quot; (it seems you swapped " and ' for eachother)
            .replaceAll(';', '&#59;');
    }
```

**Comment by Merulast** [comment]
> @Merulast Thank you for addressing this, however I did notice some issues with escapes in securityFixes.
> 
> ```js
> function securityFixes(text) {
>         return text
>             .replaceAll("'", '&quot;') // This should be &#39; (&apos; is an XML entity, but is non-standard for HTML)
>             .replaceAll('"', '&apos;') // This should be &quot; (it seems you swapped " and ' for eachother)
>             .replaceAll(';', '&#59;');
>     }
> ```

you are absolute right. I dont know how this mistake happened. urgs.

**Comment by MichaelKaaden** [comment]
@Merulast The fix seems to has added a little problem, though.

```
var result = XBBCODE.process({
     text: "<h1>Hello World!</h1>",
 });
 console.error("Errors", result.error);
 console.dir(result.errorQueue);
 console.log(result.html);
```

now produces `&lt&#59;h1&gt&#59;Hello World!&lt&#59;/h1&gt&#59;` instead of `&lt;h1&gt;Hello World!&lt;/h1&gt;`.

I prepared a PR to fix this: [31](https://github.com/patorjk/Extendible-BBCode-Parser/pull/31)

**Pull request merged**
